import re
import socket
import logging
from datetime import datetime, timezone
from urllib.parse import urlparse

import requests
import config
from services import abuseipdb_service

log = logging.getLogger(__name__)
TIMEOUT = 15
_RDAP_HEADERS = {"User-Agent": "threat-intel-platform/1.0"}
_IPV4_RE = re.compile(r"^(\d{1,3})\.(\d{1,3})\.(\d{1,3})\.(\d{1,3})$")

# Major cloud / CDN / DNS providers. Reports against these are usually generated by
# customer or end-user activity on shared address space, not the provider itself.
_INFRA_PROVIDERS = {
    "cloudflare": "Cloudflare",
    "google": "Google",
    "amazon": "Amazon Web Services",
    "aws": "Amazon Web Services",
    "microsoft": "Microsoft Azure",
    "azure": "Microsoft Azure",
    "digitalocean": "DigitalOcean",
    "oracle": "Oracle Cloud",
    "akamai": "Akamai",
    "fastly": "Fastly",
    "linode": "Linode",
    "ovh": "OVH",
    "hetzner": "Hetzner",
    "alibaba": "Alibaba Cloud",
    "vultr": "Vultr",
}
# AbuseIPDB usage types that indicate shared infrastructure rather than an end host
_INFRA_USAGE = {"data center/web hosting/transit", "content delivery network"}


def _is_ip(value: str) -> bool:
    m = _IPV4_RE.match(value)
    return bool(m) and all(0 <= int(o) <= 255 for o in m.groups())


def _clean_domain(value: str) -> str:
    if "://" in value or "/" in value:
        value = urlparse(value if "://" in value else "http://" + value).hostname or value
    return value.strip().lower().strip(".")


def _detect_provider(isp, domain, usage_type):
    """Returns (provider_name or None, is_infrastructure bool)."""
    hay = " ".join(filter(None, [isp, domain])).lower()
    for kw, name in _INFRA_PROVIDERS.items():
        if kw in hay:
            return name, True
    if (usage_type or "").strip().lower() in _INFRA_USAGE:
        return None, True
    return None, False


def _tier(score, whitelisted, is_infra):
    """Six-tier verdict. High scores always win; trust signals only lift low scores."""
    if score is None:
        return "Unknown"
    if score >= 81:
        return "Malicious"
    if score >= 61:
        return "High Risk"
    if score >= 31:
        return "Suspicious"
    if (whitelisted and score == 0) or (is_infra and score <= 10):
        return "Trusted Infrastructure"
    if score >= 11:
        return "Low Risk"
    return "Clean"


def _confidence(score, whitelisted, is_infra):
    """How certain the verdict is (not how risky). Extremes are certain; the
    middle band is genuinely ambiguous, so confidence drops there."""
    if score is None:
        return {"level": "Low", "percent": 40}
    if whitelisted and score == 0:
        return {"level": "High", "percent": 95}
    if score >= 81:
        return {"level": "High", "percent": 95}
    if score <= 10:
        return {"level": "High", "percent": 90 if is_infra else 85}
    if score >= 61:
        return {"level": "High", "percent": 85}
    if 31 <= score <= 60:
        return {"level": "Medium", "percent": 60}
    return {"level": "Medium", "percent": 72}


def _ip_factors(score, whitelisted, is_infra, provider, total_reports, is_tor, usage_type):
    """Builds the explained reason list. type is one of: positive, caveat, negative."""
    f = []
    if whitelisted:
        f.append(("Whitelisted by AbuseIPDB", "positive"))
    if score == 0:
        f.append(("Abuse confidence score is 0", "positive"))
    elif score <= 10:
        f.append((f"Low abuse confidence score ({score}/100)", "positive"))
    elif score >= 81:
        f.append((f"Very high abuse confidence score ({score}/100)", "negative"))
    elif score >= 61:
        f.append((f"High abuse confidence score ({score}/100)", "negative"))
    elif score >= 31:
        f.append((f"Elevated abuse confidence score ({score}/100)", "negative"))
    else:
        f.append((f"Moderate abuse confidence score ({score}/100)", "caveat"))

    if provider:
        f.append((f"Belongs to {provider} infrastructure", "positive"))
    elif is_infra:
        f.append(("Hosted on cloud/CDN infrastructure", "positive"))

    if total_reports:
        if (is_infra or whitelisted) and score <= 10:
            f.append((f"{total_reports} historical reports (expected for shared infrastructure)", "caveat"))
        elif score >= 31:
            f.append((f"{total_reports} abuse reports on record", "negative"))
        else:
            f.append((f"{total_reports} historical reports on record", "caveat"))

    if is_tor:
        f.append(("Tor exit node", "negative"))
    return f


def _lookup_ip(ip: str) -> dict:
    res = abuseipdb_service.check_ip(ip)
    if not res:
        return {"type": "ip", "value": ip, "verdict": "Unknown",
                "confidence": {"level": "Low", "percent": 0},
                "factors": [], "error": "AbuseIPDB not configured or lookup failed."}

    raw = res.get("raw", {})
    score = res.get("score", 0)
    whitelisted = bool(raw.get("isWhitelisted"))
    is_tor = bool(raw.get("isTor"))
    isp = raw.get("isp")
    host = raw.get("domain")
    usage = raw.get("usageType")
    total_reports = raw.get("totalReports", 0)
    last = raw.get("lastReportedAt")

    provider, is_infra = _detect_provider(isp, host, usage)
    verdict = _tier(score, whitelisted, is_infra)
    confidence = _confidence(score, whitelisted, is_infra)
    factors = _ip_factors(score, whitelisted, is_infra, provider, total_reports, is_tor, usage)

    return {
        "type": "ip",
        "value": ip,
        "verdict": verdict,
        "confidence": confidence,
        "factors": [{"text": t, "type": ty} for t, ty in factors],
        "is_infrastructure": is_infra,
        "provider": provider,
        "abuse_score": score,
        "country": raw.get("countryName") or raw.get("countryCode"),
        "country_code": raw.get("countryCode"),
        "isp": isp,
        "domain": host,
        "usage_type": usage,
        "total_reports": total_reports,
        "last_reported": last.split("T")[0] if last else None,
        "is_whitelisted": whitelisted,
        "is_tor": is_tor,
    }


def _rdap_domain(domain: str) -> dict:
    out = {"registration_date": None, "age_days": None, "registrar": None}
    try:
        r = requests.get(f"https://rdap.org/domain/{domain}",
                         headers=_RDAP_HEADERS, timeout=TIMEOUT)
        if r.status_code == 404:
            out["note"] = "No RDAP record found for this domain."
            return out
        r.raise_for_status()
        data = r.json()
        for ev in data.get("events", []):
            if ev.get("eventAction") == "registration" and ev.get("eventDate"):
                try:
                    reg = datetime.fromisoformat(ev["eventDate"].replace("Z", "+00:00"))
                    out["registration_date"] = reg.date().isoformat()
                    out["age_days"] = (datetime.now(timezone.utc) - reg).days
                except ValueError:
                    pass
                break
        for ent in data.get("entities", []):
            if "registrar" in ent.get("roles", []):
                for item in ent.get("vcardArray", [None, []])[1]:
                    if item and item[0] == "fn":
                        out["registrar"] = item[3]
                        break
                break
    except Exception as e:
        log.warning(f"[lookup] RDAP failed for {domain}: {e}")
        out["note"] = "RDAP lookup failed."
    return out


def _lookup_domain(domain: str) -> dict:
    result = {"type": "domain", "value": domain}
    result.update(_rdap_domain(domain))
    age = result.get("age_days")

    resolved_ip, ip_score, provider, is_infra = None, None, None, False
    whitelisted = False
    try:
        resolved_ip = socket.gethostbyname(domain)
    except Exception:
        pass

    if resolved_ip:
        result["resolved_ip"] = resolved_ip
        ip_res = abuseipdb_service.check_ip(resolved_ip)
        if ip_res:
            raw = ip_res.get("raw", {})
            ip_score = ip_res.get("score", 0)
            whitelisted = bool(raw.get("isWhitelisted"))
            provider, is_infra = _detect_provider(raw.get("isp"), raw.get("domain"), raw.get("usageType"))
            result["ip_abuse_score"] = ip_score
            result["ip_country"] = raw.get("countryName")
            result["ip_isp"] = raw.get("isp")

    # Verdict: host reputation dominates; very young domains are suspicious
    score_for_tier = ip_score if ip_score is not None else 0
    verdict = _tier(score_for_tier, whitelisted, is_infra)
    if age is not None and age < 30 and verdict in ("Clean", "Trusted Infrastructure", "Low Risk"):
        verdict = "Suspicious"
    result["verdict"] = verdict
    result["confidence"] = _confidence(ip_score, whitelisted, is_infra) if ip_score is not None \
        else {"level": "Low", "percent": 45}
    result["is_infrastructure"] = is_infra
    result["provider"] = provider

    # Domain factors
    f = []
    if age is not None:
        if age < 30:
            f.append((f"Domain registered only {age} days ago", "negative"))
        elif age < 180:
            f.append((f"Domain is {age} days old", "caveat"))
        else:
            yrs = round(age / 365, 1)
            f.append((f"Established domain ({yrs} years old)", "positive"))
    if result.get("registrar"):
        f.append((f"Registered via {result['registrar']}", "positive"))
    if ip_score is not None:
        if ip_score == 0:
            f.append(("Hosting IP has a clean abuse record", "positive"))
        elif ip_score >= 31:
            f.append((f"Hosting IP has an elevated abuse score ({ip_score}/100)", "negative"))
        else:
            f.append((f"Hosting IP abuse score {ip_score}/100", "caveat"))
    if provider:
        f.append((f"Hosted on {provider} infrastructure", "positive"))
    result["factors"] = [{"text": t, "type": ty} for t, ty in f]
    return result


def lookup(value: str) -> dict:
    value = (value or "").strip()
    if not value:
        return {"error": "empty input"}
    if _is_ip(value):
        return _lookup_ip(value)
    domain = _clean_domain(value)
    if not domain or "." not in domain:
        return {"error": "Enter a valid IP address or domain name."}
    return _lookup_domain(domain)
